# Generated by Django 5.1.7 on 2025-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='visualizaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
